# Generated by Django 4.0.4 on 2022-05-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='tema',
            new_name='genero',
        ),
    ]
